title: Vu Ngoc Huyen (JennVu)
logo: assess/AVa.jpg
description: Crafting captivating marketing strategies, seducing success with data-driven allure.
show_downloads: False
remote_theme: jekyll-theme-minimal
